"""PhysioCell parameters.xml emitter for nidus.

PhysioCell consumes per-simulation scalars via a `<user_parameters>`
block in its `PhysiCell_settings.xml`. This module produces a drop-in
`nidus-parameters.xml` containing every nidus parameter, with comments
carrying the citation key and confidence tier so a PhysioCell user can
read the file and trust the values.

A separate, fuller PhysioCell tissue example will land in v0.4 — that
work is specified in `docs/specs/v0.4/01-mechanistic-modeling-interop.md`
§17.2 and is a follow-on commit. This module ships the parameter-feed
side first because it's simple, stable, and immediately useful.
"""

from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import quoteattr

from nidus.load import Dataset
from nidus.models import Parameter


def _safe_units(units: str) -> str:
    """PhysioCell user_parameters use restricted unit strings."""
    return units.replace("μ", "u").replace("²", "^2").replace("³", "^3")


def _param_xml(p: Parameter) -> str:
    desc_parts: list[str] = [p.name]
    desc_parts.append(f"tier={p.tier}")
    desc_parts.append(f"review_status={p.extraction.review_status}")
    if p.primary_citation:
        cite = p.primary_citation
        if cite.doi:
            desc_parts.append(f"doi={cite.doi}")
        elif cite.pmid:
            desc_parts.append(f"pmid={cite.pmid}")
        desc_parts.append(f"citation_key={cite.key}")
    description = "; ".join(desc_parts)
    safe_id = p.id.replace(".", "__")
    return (
        f'        <{safe_id} type="double" units={quoteattr(_safe_units(p.value.units))} '
        f"description={quoteattr(description)}>"
        f"{p.value.central}"
        f"</{safe_id}>"
    )


def build_physiocell_params(ds: Dataset) -> str:
    """Return the full nidus-parameters.xml as a string.

    Output structure:
        <PhysiCell_settings>
          <user_parameters>
            <!-- per subsystem comment -->
            <maternal_cardiovascular__baseline_cardiac_output_l_per_min ...>4.6</...>
            ...
          </user_parameters>
        </PhysiCell_settings>
    """
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!--",
        "  nidus dataset, exported as PhysioCell <user_parameters>.",
        "  Generated by nidus.export.physiocell. Do not edit by hand;",
        "  re-run `nidus export --format physiocell` to regenerate.",
        "",
        "  Every parameter is annotated in its `description` attribute with",
        "  the confidence tier, review status, and primary citation. See",
        "  https://github.com/clay-good/nidus for the full provenance.",
        "-->",
        "<PhysiCell_settings>",
        "    <user_parameters>",
    ]
    # Group by subsystem with a heading comment for readability
    by_sub: dict[str, list[Parameter]] = {}
    for p in ds:
        by_sub.setdefault(p.subsystem, []).append(p)

    for sub in sorted(by_sub):
        lines.append(f"        <!-- {sub} -->")
        for p in sorted(by_sub[sub], key=lambda x: x.id):
            lines.append(_param_xml(p))
    lines.append("    </user_parameters>")
    lines.append("</PhysiCell_settings>")
    return "\n".join(lines) + "\n"


def write_physiocell(ds: Dataset, output_dir: str | Path) -> Path:
    """Write nidus-parameters.xml to a directory. Returns the file path."""
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "nidus-parameters.xml"
    path.write_text(build_physiocell_params(ds), encoding="utf-8")
    return path
